### ISSUE TITLE
Did you mean 'fix'?

### ISSUE THREAD

**Issue by Goosie** [LNP-BP/rgb-sdk#18]
After cloning rgb-sdk, cd rust-lib you get a warning: Did you mean 'fix'? Running cargo fix cargo gives updating, dowdloaded and compiling mesages. When you run cargo lipo again, the warning comes up again: mu such subcommand 'lipo' Did you mean 'fix'? What means this?
![image](https://user-images.githubusercontent.com/176074/98787907-63ecdf00-2400-11eb-8f6d-1961a149c787.png)

**Comment by zoedberg** [comment]
have you tried running `cargo install cargo-lipo`?

please note that the instructions in the `README.md` need to be fixed. use instructions for the specific bindings you want to build (currently available: node.js, android, ios)

**Comment by Goosie** [comment]
Yess thanks, that was the trick.

**Comment by Goosie** [comment]
cargo install cargo-lipo was the trick should be added in the readme file

**Comment by dr-orlovsky** [comment]
@Goosie added to the docs with https://github.com/LNP-BP/rgb-sdk/pull/20/files
