### ISSUE TITLE
Update & finalize integration APIs for fungible tokens

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-sdk#2]
This is related to
1. C bindings from `ffi`
2. Android lib & demo app from `ffi/android`
3. iOS demo app (directly using C FFI) from `ffi/ios`
4. NodeJS npm swig-based module and demo from `ffi/nodejs`

Tasks:
~~- [ ] Remove token issue procedure, since it is not required. Tokens will be issued only once, and probably with a separate command-line tool written in pure rust. It will not be a part of wallet or exchage SDKs anyway. (NB: this procedure was broken due to removal of dust limit parameter from main schema)~~
- [ ] Since transfer API is stabilized, we need to use proper arguments in c bindings (and the rest of libs) instead of encoding/decoding to JSON and passing it around
- [x] Make sure that everything builds and all demo apps work
- [ ] Add `validate` and `accept` functions to support acceptance of transfers (pending https://github.com/LNP-BP/rgb-node/issues/97)
- [x] Provide bindings for convinence functions based on implementation in https://github.com/LNP-BP/rgb-node/pull/91

**Comment by UkolovaOlga** [comment]
@dr-orlovsky are Python bindings/wrappers also required to be present in `ffi` folder in addition to android, ios and nodejs?

**Comment by dr-orlovsky** [comment]
Yes, but it can be done later, since not time-critical

**Comment by UkolovaOlga** [comment]
Python wrappers and bindings issue can be found [here](https://github.com/LNP-BP/rgb-sdk/issues/1)

**Comment by zoedberg** [comment]
I have two considerations about token issue procedure removal:

1) I've noticed that the `IssueArgs` class defined in `ffi/android/library/src/main/java/org/lnpbp/rgbnode/model/IssueArgs.java` contains the class `CoinAllocation`. This class is necessary when calling `transfer` (`public void transfer(List<String> inputs, List<IssueArgs.CoinAllocation> allocate, ... )`). I think I can just move `CoinAllocation` definition outside so I can remove the `IssueArgs.java` file. But I'd like to be sure about that 

2) For the moment the react-native demo app is doing just the token issue procedure, removing that would cause the app to have no functionality (besides being useful in showing how to integrate the library). I don't see it as a problem, but I want to be sure you've considered this

**Comment by dr-orlovsky** [comment]
1. Yes, we will need this class all around, so it will be good to move it into a separate file
2. I think we can wait with removing issuance procedure before we will have more convenience functions to demo.

The most important for now is to make sure we link with v0.1 release (and not master) of RGB Node and everything still works

**Comment by dr-orlovsky** [comment]
@zoedberg pls check the task description, there is an important update related to exposing `validate` and `accept` methods

**Comment by zoedberg** [comment]
> Provide bindings for convinence functions based on implementation in LNP-BP/rgb-node#91

for convenience functions, do you mean the methods `asset_allocations` and `output_assets`?

should I first add them to the `i9n` module on rgb-node?

**Comment by dr-orlovsky** [comment]
@zoedberg yes and yes

**Comment by zoedberg** [comment]
@dr-orlovsky have you purposely closed this issue or has github automation did it?

the task "Add validate and accept functions to support acceptance of transfers (pending LNP-BP/rgb-node#97)" requires merge of #21 (which requires the consignment decoding to be fixed first)

and the task "Since transfer API is stabilized, we need to use proper arguments in c bindings (and the rest of libs) instead of encoding/decoding to JSON and passing it around" should require #24, but since this task already has its dedicated issue, I think we can safely remove it from here

**Comment by dr-orlovsky** [comment]
It was github
