### ISSUE TITLE
Add `import_asset`, `export_asset`, `list_assets` and `invoice` methods

### ISSUE THREAD

**Issue by zoedberg** [LNP-BP/rgb-sdk#28]
After closing LNP-BP/rgb-node#117, we should add the `import_asset` and `invoice` methods

**Comment by dr-orlovsky** [comment]
I propose to have `list_asset` method as well, exposing `runtime.list`. W/o it is impossible to do a transfer after the issuance in any demo (or real-world) app

**Comment by dr-orlovsky** [comment]
BTW, invoicing does not require I9N or talking to RGB node; you can generate an invoice right in the SDK. Just construct `rgb::fungible::Invoice` object with it's data (ContractId, Outpoint, which may be constructed from tx outpoint data) and that's all

**Comment by zoedberg** [comment]
I think we should add also an `export_asset` method. @dr-orlovsky do you agree? (if yes I will add it also to LNP-BP/rgb-node#117)

**Comment by dr-orlovsky** [comment]
Yes, I think it is needed
