### ISSUE TITLE
Build NPM module for specific architectures

### ISSUE THREAD

**Issue by Jasonvdb** [LNP-BP/rgb-sdk#44]
In order to get the NodeJS bindings working for React Native we need to still compile the NPM module for the specific architectures.

`Error: dlopen(/Users/jason/Library/Developer/CoreSimulator/Devices/1B444072-AD1E-495F-8AF0-2200356C18F2/data/Containers/Bundle/Application/410AFD16-4FE8-482E-9E8C-FB6B9AF5CFA1/RgbReactNative.app/nodejs-project/Release/rgblib.node, 1): no suitable image found.`

I thought perhaps replacing `cargo build` with `cargo lipo` inside `package.json` would solve the problem at least for `aarch64-apple-ios` and  `x86_64-apple-ios`. It builds but then received this error from `node-gyp`:

```
> node ./node_modules/node-gyp/bin/node-gyp.js rebuild

  CXX(target) Release/obj.target/rgblib/swig_wrap.o
../swig_wrap.cxx:1524:3: warning: ignoring return value of function declared with 'warn_unused_result' attribute [-Wunused-result]
  obj->SetAccessor(SWIGV8_CURRENT_CONTEXT(), SWIGV8_SYMBOL_NEW(symbol), getter, setter);
  ^~~~~~~~~~~~~~~~
1 warning generated.
  SOLINK_MODULE(target) Release/rgblib.node
ld: library not found for -lrgb
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/rgblib.node] Error 1
```

Not too familiar with node-gyp and swig so not sure where the problem could be.

**Comment by dr-orlovsky** [comment]
Seems like the path for lipo-built rgb library is wrong and the compiler can’t find it. Where you put the lipo-build library? Can you do a PR with the modified script so I can play with the build myself?

**Comment by Jasonvdb** [comment]
The second error there happens when `node ./node_modules/node-gyp/bin/node-gyp.js rebuild` is called from package.json when I run `npm install` after I modifying package.json like [this](https://github.com/LNP-BP/rgb-sdk/pull/45/files). 

I was hoping this would be the solution for iOS but it's likely more involved than that.

If the npm module can be specifically built for iOS then I have a test repo [rgb-react-native](https://github.com/Jasonvdb/rgb-react-native) that is using [nodejs-mobile-react-native](https://github.com/janeasystems/nodejs-mobile-react-native)

After building you can move `rgb-sdk/bindings/npm/build/Release/` to `rgb-react-native/nodejs-assets/nodejs-project/`.

**Comment by dr-orlovsky** [comment]
> after I modifying package.json like this.

`cargo lipo` produces output library in the other directory than `cargo build`. You need to grab the file from `target/universal/release`, not `target/release`.

**Comment by Jasonvdb** [comment]
I think the problem lies with swig then? I need swig to use `target/universal/release` instead of `target/release` right?

**Comment by dr-orlovsky** [comment]
Seems so

**Comment by Jasonvdb** [comment]
We're going with the native iOS/Android wrapper for react native now so I'm no longer looking for a solution to this 👍
