### ISSUE TITLE
How to read the witness_tx.dat file?

### ISSUE THREAD

**Issue by Sudz24** [LNP-BP/rgb-sdk#58]
Hi, 

I am able to run the NodeJS demo file successfully with some fed in OUTPOINTS and PSBT. 
The created output file witness_tx.dat contains the updated PSBT that can broadcasted right?
However, I am not finding a right way to read this file and get the PSBT Hex. Can you please guide me here on this?

**Comment by zoedberg** [comment]
Hi! 

All the demos in this repository are quite old so I don't suggest spending time on them. The latest RGB release, 0.8.0, has brought many breaking changes. I suggest to follow this demo https://github.com/LNP-BP/nodes/blob/master/contrib/demo-rgb.sh which is the most updated and vialble resource at the moment.

**Comment by Sudz24** [comment]
Thank you for the quick response @zoedberg, I will look into it. 
Do we have a similar wrapper class APIs for the latest version of RGB?

**Comment by zoedberg** [comment]
Not yet, but I think this project or the new https://github.com/RGB-WG/rgb-api one will do that once all the RGB components will be stable and finalized (that should happen very soon). In the meanwhile, if you're planning to integrate RGB, I suggest getting familiar with its basic concepts. RGB does not manage wallet operations, you will need to take care of the UTXOs (especially to prevent asset burning), or depend on some other project that will do that for you.

**Comment by Sudz24** [comment]
Thank you for guiding me @zoedberg 

I tried installing the latest packages as mentioned in the demo-rgb.sh, however I get this error while trying to use the installed CLI. 

`'rgb20 binary not found: Os { code: 2, kind: NotFound, message: "No such file or directory" }'`

Do you know why this is happening? I can see the binaries under /.cargo/bin but maybe it's not installed correctly. Sorry to bother you again with an error.

**Comment by zoedberg** [comment]
I think I can help you, but this is not the correct repository where to discuss this, could you please report the issue in the https://github.com/LNP-BP/nodes/ repository?

**Comment by Sudz24** [comment]
Sure!
I will close this issue as solved, thank you.

**Comment by Sudz24** [comment]
Hi @zoedberg, can you let me know if there's any update on the RGB API with the new release? I don't see anything added to the repo since our last conversation.

**Comment by zoedberg** [comment]
Hi! As far as I know they have not been updated. My team is currently working on https://github.com/RGB-Tools/rgb-lib which provides a higher level interface to allow people with little knowledge on RGB get started easily. It provides also bindings in kotlin, swift and python. Not sure it's what you were looking for, but, if you don't want to use Rust, they are currently the fastest way for you to integrate RGB somewhere.

**Comment by Sudz24** [comment]
Oh okayy, thanks for the response @zoedberg!
I am keen on JS because I am trying to build a browser based app where the user can import their keys locally and perform transactions.
So the Python bindings, do they have the logic for all the steps - from creating asset, embedding data to verifying it?

**Comment by zoedberg** [comment]
Python bindings allow you to create, send and receive assets. 

Not sure what do you mean by "embedding data to verifying it". If you intend attaching metadata to the RGB contract yes, that's possible. For the verify part, if you intend the transfers validation, that's handled by the RGB libraries, not directly by rgb-lib. In rgb-lib the only verification we do is that an eventual file attached to the contract via its ID is present on the proxy server and that its hash matches the ID in the contract.

Your project seems similar to what [Diba](https://github.com/diba-io) is trying to achieve, probably you should give a look to [bitmask](https://github.com/diba-io/bitmask-core) too

**Comment by Sudz24** [comment]
Understood, thank you for the reply @zoedberg!! 
Do we have any prebuilt Asset Explorers for RGB - similar to Blockchain Explorer for BTC transactions?

**Comment by zoedberg** [comment]
Having an RGB explorer similar to the ones for BTC is impossible by design.

Issuance contracts are not registered on the blockchain or anywhere public that an explorer can look at. RGB assets are private and their existence is known only to the people who own or have owned the asset. Moreover also transfers are private: parties involved in the contract can see some partial graph of past transfers but no one, not even the issuer, can know where assets are once they have have been transferred to someone else.

So it's impossible to create an explorer that will detect all existing RGB assets and their transfers.

Some issuers will advertise their assets, on websites or exchanges. For example there is http://rgbex.io (not working ATM, needs to be updated) that is an RGB explorer where one can register an existing asset just to make it known to everybody

**Comment by dr-orlovsky** [comment]
@Sudz24: @zoedberg is correct. I'd like to add that I think there will be a market convergence to a specific way of distributing information about the issued RGB assets.

From LNP/BP Association we propose to use Storm network (which is build on top of Lightning Network) to publish propagate the information about assets in a decentralized way. And in this regard an explorer can be build which will use data from the lightening network/storm and present them in a nice UI.
