### ISSUE TITLE
Post-release check for v0.1.0

### ISSUE THREAD

**Issue by dr-orlovsky** [LNP-BP/rgb-sdk#8]
Today I made a final release of version 0.1 for both LNP/BP Core Library and RGB Node crates + updated corresponding docker images. We need to move to crate links in this repo and make sure everything builds and create a release here as well. As the last-minute change there was a removal of the need to provide fee size for the RGB Node in transfer request (it is now auto-computed from PSBT data), so we need to make sure that have not broke anything here.

Local changes needed:
- In https://github.com/LNP-BP/rgb-sdk/blob/master/rust-lib/Cargo.toml
    * Remove all crates from `[patch.crates-io]` section, **leave only** `zeromq-src`
    * Change RGB Node dependency on "~0.1.0" (from github path). Current master should not build here (it already have diverged and moved on work on v0.2 with Lightning)
- Change all GitHub RGB Node downloads in Dockerfile are happening from `v0.1.0` tag

Once everything work I will do a crate release for Rust bindings, and probably later we will work on NPM module release as well

**Comment by zoedberg** [comment]
> Change all GitHub RGB Node downloads in Dockerfile are happening from v0.1.0 tag

I don't understand what do you mean here, could you explain me? At the moment there's only a Dockerfile in this repo (the one for nodejs, already tested with rgb_node 0.1.0) that downloads rgb_node and all other deps using the same `Cargo.toml` used locally

**Comment by dr-orlovsky** [comment]
Right, now I see.
